version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "traffic_police_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5440:5432"

  image_storage:
    build: ./image_storage
    ports:
      - "8000:8000"

  service:
    build: ./service
    ports:
      - "8080:8080"