version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "traffic_police_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5440:5432"
    volumes:
      - pg_vol:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  service:
    build: ./service
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_URL: "postgresql://user:user@postgres:5432/traffic_police_db?sslmode=disable"
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    volumes:
      - cases_vol:/cases
      - experts_vol:/experts

volumes:
  pg_vol:
  cases_vol:
  experts_vol: