version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "traffic_police_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5440:5432"