version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "traffic_police_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5440:5432"
    volumes:
      - pg_vol:/var/lib/postgresql/data
    networks:
      - service_network

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - service_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 15s
      retries: 5

  service:
    build: ./service
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_URL: "postgresql://user:user@postgres:5432/traffic_police_db?sslmode=disable"
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - cases_vol:/cases
      - experts_vol:/experts
    networks:
      - service_network

  fine_notification:
    build: ./fine_notification
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - service_network

volumes:
  pg_vol:
  cases_vol:
  experts_vol:

networks:
  service_network:
    driver: bridge