migrateup:
	 migrate -path migrations -database "postgresql://user:user@localhost:5440/traffic_police_db?sslmode=disable" --verbose up

migratedown:
	 migrate -path migrations -database "postgresql://user:user@localhost:5440/traffic_police_db?sslmode=disable" --verbose down


