// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CheckerRepo is an autogenerated mock type for the CheckerRepo type
type CheckerRepo struct {
	mock.Mock
}

// CheckExpertExists provides a mock function with given fields: expertID
func (_m *CheckerRepo) CheckExpertExists(expertID string) (bool, error) {
	ret := _m.Called(expertID)

	if len(ret) == 0 {
		panic("no return value specified for CheckExpertExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(expertID)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(expertID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(expertID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCheckerRepo creates a new instance of CheckerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckerRepo {
	mock := &CheckerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
