// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PaginationRepo is an autogenerated mock type for the PaginationRepo type
type PaginationRepo struct {
	mock.Mock
}

// GetRecordsCount provides a mock function with given fields: table
func (_m *PaginationRepo) GetRecordsCount(table string) (int, error) {
	ret := _m.Called(table)

	if len(ret) == 0 {
		panic("no return value specified for GetRecordsCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(table)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(table)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(table)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaginationRepo creates a new instance of PaginationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaginationRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaginationRepo {
	mock := &PaginationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
