// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	dto "TrafficPolice/internal/transport/rest/dto"

	mock "github.com/stretchr/testify/mock"
)

// FinePublisher is an autogenerated mock type for the FinePublisher type
type FinePublisher struct {
	mock.Mock
}

// PublishFineNotification provides a mock function with given fields: c
func (_m *FinePublisher) PublishFineNotification(c dto.CaseWithImage) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for PublishFineNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.CaseWithImage) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFinePublisher creates a new instance of FinePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinePublisher {
	mock := &FinePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
