# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: fine_notification

on:
  push:
    paths:
      - fine_notification/**
    branches: [ "master", "main" ]
  pull_request:
    paths:
      - fine_notification/**
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build
        working-directory: ./fine_notification
        run: |
          go mod tidy
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./fine_notification

      - name: Test
        working-directory: ./fine_notification
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...

