// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ImgService is an autogenerated mock type for the ImgService type
type ImgService struct {
	mock.Mock
}

// GetImgFilePath provides a mock function with given fields: dir, id
func (_m *ImgService) GetImgFilePath(dir string, id string) (string, error) {
	ret := _m.Called(dir, id)

	if len(ret) == 0 {
		panic("no return value specified for GetImgFilePath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(dir, id)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(dir, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(dir, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveImg provides a mock function with given fields: img, filepath
func (_m *ImgService) SaveImg(img []byte, filepath string) error {
	ret := _m.Called(img, filepath)

	if len(ret) == 0 {
		panic("no return value specified for SaveImg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = rf(img, filepath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewImgService creates a new instance of ImgService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImgService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImgService {
	mock := &ImgService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
